### ISSUE TITLE
Final task list for 1.0

### ISSUE THREAD

**Issue by sebastiangreger** [sebastiangreger/kirby3-commentions#55]
- [x] Render Hx in comments as p-tags with class :heavy_check_mark: https://github.com/sebastiangreger/kirby3-commentions/pull/54/commits/ee1ef92f95a6b3d768271e65bb49703d8e6fca00
- [x] Enable/disable comments/webmentions by template :heavy_check_mark: #56 
- [x] Improve "no cronjob last 24h" warning to take into account fresh installs :heavy_check_mark: https://github.com/sebastiangreger/kirby3-commentions/commit/9f631e3a76d99f1decfdd1922b105e9e48cf9646 + https://github.com/sebastiangreger/kirby3-commentions/pull/56/commits/a4eb23c3f1611dc3411499ab921d52304cdbf22f
- [x] Sibling plugin with dependencies under LGPL :heavy_check_mark: https://github.com/sebastiangreger/kirby3-commentions/issues/55#issuecomment-626178488
- [x] Update installation instructions based on sibling plugin :heavy_check_mark: https://github.com/sebastiangreger/kirby3-commentions/commit/b039c1fb3e524cdc0fee6f787d96d6394be8c992
- [x] Parse markdown for comments only (not for webmentions) :heavy_check_mark: https://github.com/sebastiangreger/kirby3-commentions/pull/54/commits/7c1475c792b2aa78bf9eb05a87297784a7aa8643
- [x] Final test of migration tool
- [x] Quick check that the comment form help text corresponds with implementation
- [x] Add a dialog window for editing comments :heavy_check_mark:
- [x] Add page-specific settings (comments/webmentions on/off etc.) :heavy_check_mark:
- [x] Edit comments in Panel :heavy_check_mark:
- [x] Review defaults and settings for privacy-by-design and privacy-by-default --> change default by template :heavy_check_mark:
- [x] Final test run with virtual pages :heavy_check_mark:

#### Optional/tbd:
- [x] move `/classes` to `/lib` to conform with Kirby's [Plugin best practices](https://getkirby.com/docs/guide/plugins/best-practices) :heavy_check_mark:
- [x] ~~Convert semantic inline markup (`<em>`, `<strong>`, `<del>`) to presentational equivalents (`<i>`, `<b>`, `<s>`), analogue to transformation bevavior of headlines.~~ Just converted `<strike>` => `<s>` ✔️ 87bc6e3 

#### Before launch:
- [x] Update version numbers across files
- [x] Update screenshots
- [x] Final check on readme #40
- [x] Re-activate cache from development ✔️ fc398f7 
- [x] Publish on Packagist @sebastiangreger #12 

#### Things/ideas moved to possible future updates:
- Add HTML whitelist to Readme, so devs know what CSS rules need to be provided for displaying comments. @fabianmichael

**Comment by fabianmichael** [comment]
@sebastiangreger I published the sibling plugin at https://github.com/avoskitchen/kirby-sanitizer, please give it a try and tell me if it works for you.

**Comment by sebastiangreger** [comment]
> @sebastiangreger I published the sibling plugin at https://github.com/avoskitchen/kirby-sanitizer, please give it a try and tell me if it works for you.

Works like a charm; I updated the Readme accordingly: https://github.com/sebastiangreger/kirby3-commentions/commit/b039c1fb3e524cdc0fee6f787d96d6394be8c992

**Comment by sebastiangreger** [comment]
> Convert semantic inline markup (<em>, <strong>, <del>) to presentational equivalents (<i>, <b>, <s>), analogue to transformation bevavior of headlines.

This is an interesting one. I've been thinking about it back and forth - there are good arguments for and against. Since comments presented are merely "citations", I too believe that the original semantics are not so important. And we indeed already "loose" semantics as we render headlines as paragraphs.  On the other hand, there is not really much of a benefit in changing them, as visually they will be the same, and for assistive technology they would simply be described more "visually" rather than based on their meaning.

Since this is not a critical feature, I would suggest to leave this as is for now - unless you have strong feelings about it and can spare the time; no objections from my side, of course.

**Comment by fabianmichael** [comment]
@sebastiangreger No, no strong feelings, just thought it would lead to better consistency across the plugin. But in practice, it should not have any effect whatsoever. As far as I know, most screen reader (for example) are ignoring `<em>`, `<strong>` etc. and do not pronounce their contents differently.

I’ve been using `<em>` and `<strong>` exclusively when XHTML was still a thing and found it to be some kind of relief, when the definitions of `<b>`, `<i>` etc. where updated for HTML5 and the whole thing finally made sense.  However, this is probably irrelevant for most use-cases and I bet that these are not used correctly in most cases either. Reminds me a bit of `<acronym>` vs `<abbr>` or the `<q>` element. Unless you are dealing with scientific documents, written by experienced authors, you cannot be sure that people really understand the differences between all of these. Maybe it’s just fine to keep tags as is and jsut do sanitization.

I just checked the list again and added a transformer for turning `<strike>` elements into `<s>`, because the former is obsolete in the HTML5 standard.

**Comment by sebastiangreger** [comment]
Great, thank you for those recent commits! :bowing_man: 

Now we are really close. I did another editing round on the readme, fixed some small issues I discovered as I tested with "real-life" data, and unified the version number to be 1.0.0-rc.1 - sounds nicer than the eternal "beta" this had been in for a year now ;)
